### ISSUE TITLE
Code for including ignored files does not actually exist

### ISSUE THREAD

**Issue by mateuszradomski** [dalance/ptags#95]
Hi,

I had problems with the option `--include-ignored`. Meaning that no matter if the option was set or omitted the output was always the same. Looking into the source code https://github.com/dalance/ptags/blob/4ff2a89d401889a4d9cccc247fdafeefb79cdf90/src/bin.rs#L82 this bool is never used anywhere, so the logic for including the ignored files is not preset in the code.

Are you able to implement that yourself or are you accepting PRs? :))

**Comment by dalance** [comment]
Yes. I welcome to accept PR.

**Comment by dalance** [comment]
Sorry for the late reply.
I'll check it.
